set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)

set(CMAKE_C_COMPILER_TARGET i686-pc-windows-gnu)
set(CMAKE_CXX_COMPILER_TARGET i686-pc-windows-gnu)
set(CMAKE_ASM_COMPILER_TARGET i686-pc-windows-gnu)

set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_LINKER lld)

set(CMAKE_C_STANDARD_INCLUDE_DIRECTORIES "")
set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES "")

set(CMAKE_C_FLAGS_INIT "-nostdinc")
set(CMAKE_CXX_FLAGS_INIT "-nostdinc")

set(CMAKE_EXE_LINKER_FLAGS_INIT "-nostdlib")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-nostdlib")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "-nostdlib")

set(CMAKE_C_STANDARD_LIBRARIES "")
